/* Copyright
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

declare namespace hlsjs {
  export type MediaPlayerEvent =
  | 'hlsAudioTracksUpdated'
  | 'hlsAudioTrackLoaded'
  | 'hlsAudioTrackLoading'
  | 'hlsAudioTrackSwitched'
  | 'hlsAudioTrackSwitching'
  | 'hlsBackBufferReached'
  | 'hlsBufferAppended'
  | 'hlsBufferAppending'
  | 'hlsBufferCodecs'
  | 'hlsBufferCreated'
  | 'hlsBufferEos'
  | 'hlsBufferFlushed'
  | 'hlsBufferFlushing'
  | 'hlsBufferReset'
  | 'hlsCuesParsed'
  | 'hlsDestroying'
  | 'hlsError'
  | 'hlsFpsDrop'
  | 'hlsFpsDropLevelCapping'
  | 'hlsFragBuffered'
  | 'hlsFragChanged'
  | 'hlsFragDecrypted'
  | 'hlsFragLoaded'
  | 'hlsFragLoading'
  | 'hlsFragLoadEmergencyAborted'
  | 'hlsFragParsed'
  | 'hlsFragParsingInitSegment'
  | 'hlsFragParsingMetadata'
  | 'hlsFragParsingUserdata'
  | 'hlsInitPtsFound'
  | 'hlsKeyLoaded'
  | 'hlsKeyLoading'
  | 'hlsLevelsUpdated'
  | 'hlsLevelLoaded'
  | 'hlsLevelLoading'
  | 'hlsLevelPtsUpdated'
  | 'hlsLevelSwitched'
  | 'hlsLevelSwitched'
  | 'hlsLevelUpdated'
  | 'hlsLiveBackBufferReached'
  | 'hlsManifestLoaded'
  | 'hlsManifestLoading'
  | 'hlsManifestParsed'
  | 'hlsMaxAutoLevelUpdated'
  | 'hlsMediaAttached'
  | 'hlsMediaAttaching'
  | 'hlsMediaDetached'
  | 'hlsMediaDetaching'
  | 'hlsNonNativeTextTracksFound'
  | 'hlsSteeringManifestLoaded'
  | 'hlsSubtitleFragProcessed'
  | 'hlsSubtitleTracksCleared'
  | 'hlsSubtitleTracksUpdated'
  | 'hlsSubtitleTrackLoaded'
  | 'hlsSubtitleTrackLoading'
  | 'hlsSubtitleTrackSwitch';
}