  export const REQUEST_PORT_TIMEOUT = 5100;
  export const REQUEST_PORT_INTERVAL = 250;
  export const SETTING_PREVIEW_THROTTLE_TIME = 8000;
  export const SETTING_PREVIEW_TIME_NEEDED = SETTING_PREVIEW_THROTTLE_TIME + 2000;
  export const MESSAGE_PORT_NAME = "SAMPLE_PORT"
  export const DYNAMIC_PREVIEW_SERVICE_ID = "4hKkWyp7UR.dynamicPreview";
  export const STATIC_PREVIEW_SERVICE_ID = "4hKkWyp7UR.staticPreview";

