/* Copyright
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

declare namespace dashjs {
  export type MediaPlayerEvent =
  | 'adaptationSetRemovedNoCapabilities'
  | 'astInFuture'
  | 'baseUrlsUpdated'
  | 'bufferStalled'
  | 'bufferStateChanged'
  | 'bufferLevelUpdated'
  | 'bufferLoaded'
  | 'canPlay'
  | 'canPlayThrough'
  | 'captionContainerResize'
  | 'captionRendered'
  | 'conformanceViolation'
  | 'contentSteeringRequestCompleted'
  | 'dynamicToStatic'
  | 'error'
  | 'eventModeOnReceive'
  | 'eventModeOnStart'
  | 'fragmentLoadingAbandoned'
  | 'fragmentLoadingProgress'
  | 'fragmentLoadingStarted'
  | 'inbandPrft'
  | 'public_keyAdded'
  | 'public_keyError'
  | 'public_keyMessage'
  | 'public_keySessionClosed'
  | 'public_keySessionCreated'
  | 'public_keySessionRemoved'
  | 'public_keySessionUpdated'
  | 'public_keyStatusesChanged'
  | 'public_keySystemAccessComplete'
  | 'public_keySystemSelected'
  | 'public_licenseRequestComplete'
  | 'public_licenseRequestSending'
  | 'log'
  | 'manifestLoaded'
  | 'manifestLoadingFinished'
  | 'manifestLoadingStarted'
  | 'manifestValidityChanged'
  | 'metricsChanged'
  | 'metricAdded'
  | 'metricChanged'
  | 'metricUpdated'
  | 'periodSwitchCompleted'
  | 'periodSwitchStarted'
  | 'playbackEnded'
  | 'playbackError'
  | 'playbackLoadedData'
  | 'playbackMetaDataLoaded'
  | 'playbackNotAllowed'
  | 'playbackPaused'
  | 'playbackPlaying'
  | 'playbackProgress'
  | 'playbackRateChanged'
  | 'playbackSeeked'
  | 'playbackSeeking'
  | 'playbackStalled'
  | 'playbackStarted'
  | 'playbackTimeUpdated'
  | 'playbackVolumeChanged'
  | 'playbackWaiting'
  | 'public_protectioncreated'
  | 'public_protectiondestroyed'
  | 'qualityChangeRendered'
  | 'qualityChangeRequested'
  | 'representationSwitch'
  | 'streamActivated'
  | 'streamDeactivated'
  | 'streamInitialized'
  | 'streamInitializing'
  | 'streamTeardownComplete'
  | 'streamUpdated'
  | 'allTextTracksAdded'
  | 'textTrackAdded'
  | 'throughputMeasurementStored'
  | 'trackChangeRendered'
  | 'ttmlParsed'
  | 'ttmlToParse'
}