name: Sync Repositories 

on:
  workflow_dispatch

jobs:
  tests:
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          fetch-depth: 1

      - name: Use Node.js v22.11
        uses: actions/setup-node@v3
        with:
          node-version: 22.11
          cache: ''

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  sync:
    runs-on: self-hosted
    needs: tests

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          fetch-depth: 1
      
      - name: Fetch all necessary refs
        run: |
          git fetch --unshallow  # This will fetch the remaining refs without fetching full history
          git fetch origin main  # Fetch additional references, like the latest commit from 'main'


      - name: Remove .github folder to avoid copying workflows
        run: |
            git rm -r --cached .github 
            git commit -m "Remove .github folder"

      - name: Setup SSH
        run: |
          echo "${{ secrets.SYNC_REPOS_DEPLOY_KEY }}" > ~/.ssh/ghActionsTest
          chmod 600 ~/.ssh/ghActionsTest
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global core.sshCommand "ssh -i ~/.ssh/ghActionsTest -o StrictHostKeyChecking=no"

      - name: Push to destination repository
        run: |
          git remote set-url origin git@github.com:SamsungDForum/tizen-tv-vod-ref-app.git
          git push origin main:main --force        

  notify:
    runs-on: self-hosted
    if: ${{ always() }}
    needs: [tests, sync]

    env:
      TRIGGER: ${{ github.event_name }}
      BRANCH: ${{ github.ref_name }}
      WEBHOOK: ${{ secrets.MM_WEBHOOK_URL }}
      WORKFLOW: ${{ github.workflow }}
      ACTION: ${{ github.event.head_commit.message }}
      ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      REPO: ${{ github.repository }}
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      USER: ${{ github.triggering_actor }}
      USER_URL: ${{ github.server_url }}/${{ github.triggering_actor }}
      TESTS_RESULT: ${{ needs.tests.result }}
      SYNC_RESULT: ${{ needs.sync.result }}
    steps:
      - name: Notify to Mchat
        if: always()
        uses: CODE-Actions/8398a7-action-slack@v3
        with:
            status: custom
            fields: job,took
            custom_payload: |
                {
                  attachments: [{
                    color: '${{ needs.tests.result }}' === 'success' && '${{ needs.sync.result }}' === 'success'  ? 'good' : 'danger',
                    text: `
                    \n**Action: **[${process.env.TRIGGER}](${process.env.ACTION_URL})\n**By:** [${process.env.USER}](${process.env.USER_URL})\n**Branch:** ${process.env.BRANCH}\n**Repo:** [${process.env.REPO}](${process.env.REPO_URL})\n**Tests: ** ${process.env.TESTS_RESULT}\n**Synchronization: ** ${process.env.SYNC_RESULT}`
                  }]
                }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
